name: workflow
on: push

jobs:
  job-1: 
    runs-on: ubuntu-24.04
    steps:
       - name: print hello all
         run: echo "hello all"
       - name: print iam the king
         run: echo "iam the idiot"
       - name: print cpu infro
         run:  lscpu
       - name: print mem info
         run: lsmem
